### PR TITLE
Image,input

### PR DESCRIPTION
**Pull request by xsaurabhsuthar**
Image, Input component added.

### CODE REVIEW

**Review by manismk — APPROVED** [review]
Just Some suggestions:
image
- You can change the input text color as it doesn't have enough contrast ratio with background.
-  Also after input is given you can make the label fixed at top itself because if it collapses the input text and label text overlaps as shown in age input above.

**Comment by xsaurabhsuthar** [comment]
image
Thanks Manish. I have fixed it.

**Review by ikkurthis1998 — APPROVED** [review]
I like the way you added different colours to each type of input. Awesome work!

**Comment by xsaurabhsuthar** [comment]
Thanks @ikkurthis1998 and @manismk  for the review.

**Pull request merged**
