### PR TITLE
Alert,button

### PR DESCRIPTION
**Pull request by xsaurabhsuthar**
Alert, Button component added.

### CODE REVIEW

**Comment by xsaurabhsuthar** [comment]
https://deploy-preview-2--morpho-ui-css-docs.netlify.app/components/button/button
https://deploy-preview-2--morpho-ui-css-docs.netlify.app/components/alert/alert

**Review by Ash-D23 — APPROVED** [review]
looks good, hover effect can be added on alert and button

**Comment by xsaurabhsuthar** [comment]
Thanks, @Ash-D23. Will surely add it with responsiveness.

**Review by samflab — CHANGES_REQUESTED** [review]
Reduce the width of the alert msgs and remove the glow bottom border from the navbar, it doesn't look good.

**Comment by xsaurabhsuthar** [comment]
Thanks, @samflab. I've made the necessary changes.

**Comment by xsaurabhsuthar** [comment]
https://deploy-preview-2--morpho-ui-css-docs.netlify.app/components/alert/alert

**Review by NtshVrm — APPROVED** [review]

**Review by NtshVrm — APPROVED** [review]

**Review by NtshVrm — APPROVED** [review]

**Review by shraddha15-creator — APPROVED** [review]

**Pull request merged**
